services:
  saucehunter:
    image: python:3.12-slim
    container_name: saucehunter
    volumes:
      - /path/to/config:/app
    working_dir: /app
    command: >
      /bin/sh -c "
      apt-get update &&
      apt-get install -y git &&
      mkdir -p /tmp/saucehunter &&
      if [ -f /app/config.py ]; then mv /app/config.py /tmp/saucehunter/; fi &&
      find /app -mindepth 1 -delete &&
      git clone --depth 1 --branch main https://github.com/Furglitch/SauceHunter.git . &&
      if [ -f /tmp/saucehunter/config.py ]; then mv /tmp/saucehunter/config.py /app/; fi &&
      pip install -r requirements.txt --root-user-action ignore &&
      python3 -u main.py"