services:
  saucehunter:
    image: python:3.12-slim
    container_name: tele-saucehunter
    volumes:
      - ${CONFIG}/PY/saucehunter:/app/saucehunter
    working_dir: /app/saucehunter
    command: >
      /bin/sh -c "
      apt-get update &&
      apt-get install -y git &&
      mkdir -p /tmp/saucehunter &&
      if [ -f /app/saucehunter/config.py ]; then mv /app/saucehunter/config.py /tmp/saucehunter/; fi &&
      find /app/saucehunter -mindepth 1 -delete &&
      git clone --depth 1 --branch main https://github.com/Furglitch/SauceHunter.git . &&
      if [ -f /tmp/saucehunter/config.py ]; then mv /tmp/saucehunter/config.py /app/saucehunter/; fi &&
      pip install -r requirements.txt --root-user-action ignore &&
      python3 -u main.py"